jobs:
  build:
    continue-on-error: ${{ matrix.experimental }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -V --file pom.xml --no-transfer-progress -DtrimStackTrace=false -P-use-toolchains
    strategy:
      fail-fast: false
      matrix:
        experimental:
        - false
        java:
        - 8
        - 11
        - 17
        os:
        - ubuntu-latest
        - macos-latest
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
permissions:
  contents: read
